FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    TZ=Asia/Taipei

WORKDIR /app

RUN pip install --no-cache-dir \
    pandas \
    SQLAlchemy \
    pymysql \
    openpyxl

COPY . /app

CMD ["python", "excel2db.py"]
